name: Workflow for TW Coursework
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker image
      run: docker build -f sql/Dockerfile -t sql/dockerfile:latest .

    - name: Unit Tests
      run: mvn -Dtest=com.napier.sem.MyTest test
     
    - name: Package and Run docker compose
      run: |
         mvn package -DskipTests
         docker-compose up --abort-on-container-exit

