name: Workflow for TW Coursework

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Java with Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          maven-version: '3.8.1'

      - name: Build JAR
        run: mvn clean install
        working-directory: master

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          cd path/to/your/project/sql
          sudo docker build -t sql/sql-server.dockerfile:latest .
          sudo docker push sql/sql-server.dockerfile:latest

