name: Workflow for TW Coursework

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Java with Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build JAR
        run: mvn clean install

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          cd sql/world.sql
          sudo docker build -t sql-server-image:latest -f sql-server.dockerfile .
          sudo docker push sql-server-image:latest

